source 'https://rubygems.org'
gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'logger'

gem 'jekyll', '>= 3.9.0'
gem 'jekyll-feed', '0.15.1'
gem 'jekyll-paginate', '1.1.0'
gem 'jekyll-sass-converter', '1.3.0'
gem 'kramdown', '2.5.1'
gem 'kramdown-parser-gfm'
gem 'rouge', '1.10.1'
gem 'jekyll-redirect-from'
gem 'tzinfo', '2.0.2'
gem 'tzinfo-data', '1.2020.1'
